---
swagger: "2.0"
info:
  description: "Sensor reader for the Raspberry PI"
  version: "0.0.1"
  title: "RPi Environment Sensors Reader"
host: "localhost:8765"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"
paths:
  /sensors:
    get:
      tags:
      - "Sensors"
      description: "The list of the supported sensors.\n"
      operationId: "getSensors"
      parameters: []
      responses:
        200:
          description: "Successfully read sensors list."
          schema:
            $ref: "#/definitions/sensorList"
      x-swagger-router-controller: "Sensors"
  /sensors/bme280:
    get:
      tags:
      - "Sensors"
      description: "Read data from a BME280.\n"
      operationId: "readBme280"
      parameters: []
      responses:
        200:
          description: "Read successful"
          schema:
            $ref: "#/definitions/bme280Data"
        404:
          description: "Sensor not available"
      x-swagger-router-controller: "Sensors"
  /sensors/weather:
    get:
      tags:
      - "Sensors"
      description: "Read Wind data from the Wind Rack\n"
      operationId: "readWind"
      parameters: []
      responses:
        200:
          description: "Read successful"
          schema:
            $ref: "#/definitions/weatherStationData"
        404:
          description: "Sensor not available"
      x-swagger-router-controller: "Sensors"
definitions:
  sensorList:
    type: "array"
    description: "The list of the available sensors"
    items:
      type: "string"
      description: "Sensor Name or ID"
  bme280Data:
    type: "object"
    properties:
      temperature:
        type: "number"
        description: "temperature in Celcius"
      pressure:
        type: "number"
        description: "atmospheric pressure in hPa"
      humidity:
        type: "number"
        description: "relative humidity in %"
      altitude:
        type: "number"
        description: "altitude above sea level in meters"
    description: "Data returned by the BME280. `Pressure`, `Temperature`, `Humidity`,\
      \ and `Altitude`."
  weatherStationData:
    type: "object"
    properties:
      temperature:
        type: "number"
        description: "temperature in Celcius"
      pressure:
        type: "number"
        description: "atmospheric pressure in hPa"
      humidity:
        type: "number"
        description: "relative humidity in %"
      windspeed:
        type: "number"
        description: "wind speed in knots"
      winddir:
        type: "integer"
        description: "true wind direction in degrees"
      rain:
        type: "integer"
        description: "precipitation, in mm/h"
    description: "Data returned by the Weather Station. `Pressure`, `Temperature`,\
      \ `Humidity`, `Wind Speed`, `Wind Direction` and `Rain`."
